import MDSplus as mds
import matplotlib.pyplot as plt
import numpy as np

delay = np.array([0, 0.5, 1, 1.5, 2, 3, 4, 5])
data = np.array([])
energy = np.array([])
for shot_number in np.array([1027, 1028, 1029, 1031, 1032, 1033, 1034, 1035]):
    tree = mds.Tree("mpts_manual", shot_number, mode='ReadOnly')
    camera2 = tree.getNode("\\Phantom2")
    Ed = tree.getNode("\\OPHIRENERGYDIRECT").data()
    data2 = camera2.SIGNAL.getData().data()
    total = data2[:, 200:270, :].sum(axis=(1, 2))
    data = np.append(data, np.sum(total - total[100:].mean()))
    energy = np.append(energy, Ed)

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(delay, data / (energy * 70 * 512), 'o')
ax.set_title(r'Stray light as function of the triggering time (gate width=1$\mu$s)')
ax.set_ylabel(r'Counts / (pixel * energy)')
ax.set_xlabel(r'Trigger time [$\mu$s]')
ax.set_ylim(0, 100)
ax.set_xlim(-0.25, 4.25)
ax.grid(True)
plt.tight_layout()
plt.savefig("Stray light vs Triggering time (1us gate).png")
plt.show()


int_time = np.array([5, 4, 3, 2.5, 2, 1.5, 1])
data = np.array([])
energy = np.array([])
for shot_number in np.array([1041, 1042, 1044, 1045, 1046, 1047, 1048]):
    tree = mds.Tree("mpts_manual", shot_number, mode='ReadOnly')
    camera2 = tree.getNode("\\Phantom2")
    Ed = tree.getNode("\\OPHIRENERGYDIRECT").data()
    data2 = camera2.SIGNAL.getData().data()
    total = data2[:, 200:270, :].sum(axis=(1, 2))
    data = np.append(data, np.sum(total - total[100:].mean()))
    energy = np.append(energy, Ed)

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(int_time, data / (energy * 70 * 512), 'o')
ax.set_title('Stray light as function of gate width (delay=500ns)')
ax.set_ylabel(r'Counts / (pixel * energy)')
ax.set_xlabel(r'Gate width [$\mu$s]')
ax.set_ylim(0, 120)
ax.set_xlim(0.75, 5.25)
ax.grid(True)
plt.tight_layout()
plt.savefig("Stray light vs gate width (0.5us delay).png")
plt.show()

delay = np.array([0, 0.5, 1, 1.5, 2, 2.5, 3, 4])
data = np.array([])
energy = np.array([])
for shot_number in np.array([1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060]):
    tree = mds.Tree("mpts_manual", shot_number, mode='ReadOnly')
    camera2 = tree.getNode("\\Phantom2")
    Ed = tree.getNode("\\OPHIRENERGYDIRECT").data()
    data2 = camera2.SIGNAL.getData().data()
    total = data2[:, 200:270, :].sum(axis=(1, 2))
    data = np.append(data, np.sum(total - total[100:].mean()))
    energy = np.append(energy, Ed)

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(delay, data / (energy * 70 * 512), 'o')
ax.set_title('Stray light as function of the triggering time (gate width=200ns)')
ax.set_ylabel(r'Counts / (pixel * energy)')
ax.set_xlabel(r'Trigger time [$\mu$s]')
ax.set_ylim(0, 50)
ax.set_xlim(-0.25, 4.25)
ax.grid(True)
plt.tight_layout()
plt.savefig("Stray light vs Triggering time (200ns gate).png")
# plt.show()
